# Generated by Django 5.2.4 on 2025-07-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(unique=True)),
                ('published_date', models.DateTimeField()),
                ('summary', models.TextField()),
            ],
        ),
    ]
