# Generated by Django 5.2.4 on 2025-07-22 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testy', '0002_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='published_date',
            new_name='published',
        ),
    ]
